Links: Linkuri
EditApplicant: Editați solicitantul
NewApplicant: Solicitant nou
EditCategory: Editați categoria
BlankValueResetsCategory: O valoare goală va reseta categoria
NewSubdivision: Subdiviziune nouă
FieldRequired: Câmpul este obligatoriu
EditDivision: Editați diviziunea
NewDivision: Diviziune nouă
NewPosition: Poziție nouă
EditSkill: Editați abilitate
EditTheFormAndSavePlease: Vă rugăm să editați formularul și să salvați
FillOutTheFormAndSavePlease: Vă rugăm să completați formularul și să salvați
UseCaseDiagram: Diagrama cazurilor de utilizare
SelectPositionToRankCandidates: Selectați o poziție pentru a clasifica candidații
Docs: Documentația
WelcomeTo: Bun venit la
EntityRelationshipDiagram: Diagrama entitate - relație
ErDiagram: Diagrama ER
BasicEntities: Entități de bază
RecordEdited: Înregistrare editată
RecordDeleted: Înregistrare ștearsă
RecordAdded: Înregistrare adăugată
NewSkillAdded: A fost adăugată o nouă abilitate
AdditionalName: Al doilea prenume
GivenName: Nume
FamilyName: Numele de familie
AppSkillAlreadyExists: Competența deja adăugat pentru acest solicitant
JobSkillAlreadyExists: Competența deja adăugată pentru această poziție
InvalidEndDay: Data de încheiere nevalidă
DuplicateName dupName@Text: Nume duplicat: "#{dupName}"
DuplicateCode: Cod duplicat
Expand: Extinde
Collapse: Restrânge
TotalValue totalValue@Text: Valoarea totală: #{totalValue}
AggregatedValue v@Text: Valoarea agregată #{v}
CumulativeWeightNotNormal: Ponderea cumulativă nu este în intervalul 0-1
WeightNotNormal: Ponderea nu este normalizată în intervalul 0-1
Toggle: Comutare
ExpertAssessment: Evaluarea expertului
CalculationAnalysis: Analiza calculelor
ShowTop: Afișează top
Top: Top
FirstN n@Int: Primele #{show n}
ShowFirstN n@Int: Afișați primele #{show n}
ShowFirst: Afișați primele
Sections: Secțiuni
Photo: Foto
EnterNewValue: Introduceți o valoare nouă
NewValue: Valoare nouă
Age: Vârstă
Attributes: Atribute
Birthday: Zi de nastere
Tag: Tag
Tags: Tag-uri
Label: Etichetă
Labels: Etichete
RemoveSubdivision: Eliminați subdiviziunea
AddSubdivision: Adăugați subdiviziune
Division: Diviziune
Divisions: Diviziuni
NumberOfCandidates: Numărul de candidați
EnterNewName: Introduceți un nume nou
Category: Categorie
CreateCategory: Creați o categorie
Categories: Categorii
InQuotes x@Text: "#{x}"
EditSkills: Editați competențele
NSkills: nr. competențe
NumberOfSkills: Numărul de competențe
Breadcrumbs: Pesmeturi
Undefined: Nedefinit
Details: Detalii
NotFound: Nu a fost găsit
Overview: Prezentare generală
SeeLink: Vezi
CreatePosition: Creați poziție
EditPosition: Editați poziția
Actions: Acțiuni
Back: Înapoi
Candidate: Candidat
SelectApplicants: Selectați solicitanții
SelectPosition: Selectați poziția
SelectAPosition: Selectați o poziție
InvalidArguments: Argumente nevalide
NumberSign: nr.
Position: Poziţie
DayEnd: Data de sfârșit
DayStart: Data de început
Id: Id
Weight: Pondere
SelectFromList: Selectați din listă
Select: Selectați
Close: Închide
Patronymic: Patronimic
Surname: Nume de familie
Name: Nume
FullName: Numele complet
Applicants: Solicitanţi
Applicant: Solicitant
NoDataFound: Nu au fost găsite date
RowsPerPage: Înregistrări pe pagină
Last: Ultimul
Next: Următorul
Previous: Anterior
First: Primul
PaginationLabel s@Int e@Int n@Int: Înregistrare #{show s} - #{show e} din #{show n}
Pagination: Paginaţie
Clear: Ștergeți
InvalidFormData: Date de formular nevalide
ReallyRemove: Chiar doriți să eliminați această înregistrare?
ReallyDelete: Chiar doriți să ștergeți această înregistrare?
PleaseConfirm: Vă rugăm să confirmați
Remove: Eliminare
Delete: Șterge
Edit: Editați
InputForm: Formular de intrare
NewSkill: Abilitate nouă
Description: Descriere
Denom: Nume
Code: Cod
Cancel: Anulare
Save: Salvați
Add: Adăuga
Search: Căutare
Skill: Aptitudine
Skills: Aptitudini
Positions: Poziții
Candidates: Candidați
Profile: Profil
Exit: Ieșire
HomePage: Pagina principală
Home: Acasă
ToggleNavigation: Comutare navigare
AppName: Candidat
MetaKeywords: Clasament, aptitudini, agregare, ierarhic
MetaDescription: Clasament ierarhic, Selectarea candidaților pe baza unei ierarhii de atribute, Agregarea clasamentelor ierarhice a competențelor

Doc1: Clasamentul candidaților
Doc11: Această aplicație oferă o metodă simplă de agregare a clasamentelor ierarhice.
Doc111: Aplicația ajută la luarea deciziilor cu privire la selecția candidaților pe baza unei ierarhii de atribute, abilități și ponderea acestora
Doc12: Abilitățile cerute de un loc de muncă ar trebui să fie definite în dicționar
Doc13: Posturile de muncă și competențele lor necesare sunt definite în secțiune
Doc14: Solicitanții și abilitățile lor sunt adăugate în secțiune
Doc15: Pentru fiecare post se calculează ratingul candidaților, iar rezultatul este disponibil la linkul „Candidat”
Doc16: Tot în secțiunea „Candidați” sunt oferite mai multe opțiuni pentru calcularea ratingului candidaților
Doc18: O abilitate este identificată printr-un cod scurt. Are un nume și o descriere. O abilitate poate fi un atribut al unei poziții și/sau al unui solicitant.
Doc19: O Poziție este identificată printr-un cod. I se atribuie un nume, o dată de început, o dată de încheiere și opțional o diviziune. De asemenea, are o relație multi-la-mulți cu Skills. Fiecărei relații „Poziție – Abilitate” i se atribuie ponderea Abilității sau a grupului. Abilitățile pot fi grupate. Și grupurile pot fi grupate în continuare într-o ierarhie.
Doc20: Un solicitant este entitatea ale cărei abilități vor fi comparate cu abilitățile necesare pentru o poziție.
Doc21: Un candidat este un solicitant ale cărui abilități au fost comparate cu cele ale unei anumite poziții și pentru care se calculează o pondere (evaluare) agregată pentru a-l diferenția de alți candidați pentru aceeași poziție.