CandidateRanking: Ранжирование кандидатов
PersonalData: Личные данные
Links: Ссылки
EditApplicant: Редактировать соискатель 
NewApplicant: Новый соискатель
EditCategory: Редактировать категорию
BlankValueResetsCategory: Пустое значение обнулит категорию
NewSubdivision: Новое подразделение
FieldRequired: Поле обязательно для заполнения
EditDivision: Редактировать подразделение
NewDivision: Новое подразделение
NewPosition: Новая должность
EditSkill: Редактировать навык
EditTheFormAndSavePlease: Пожалуйста, отредактируйте форму и сохраните
FillOutTheFormAndSavePlease: Пожалуйста, заполните форму и сохраните
UseCaseDiagram: Диаграмма вариантов использования
SelectPositionToRankCandidates: Выберите позицию для ранжирования кандидатов
Docs: Документация
WelcomeTo: Добро пожаловать в
EntityRelationshipDiagram: Диаграмма отношений сущностей
ErDiagram: ER-диаграмма
BasicEntities: Основные сущности
RecordEdited: Запись отредактирована
RecordDeleted: Запись удалена
RecordAdded: Запись добавлена
NewSkillAdded: Добавлен новый навык
AdditionalName: Отчество
GivenName: Имя
FamilyName: Фамилия
AppSkillAlreadyExists: Навык уже существует для этого соискателя
JobSkillAlreadyExists: Навык уже существует для этой должности
InvalidEndDay: Недопустимая дата окончания
DuplicateName dupName: Дублирующееся наименование: «#{dupName}»
DuplicateCode: Дублирующийся код
Expand: Развернуть
Collapse: Свернуть
TotalValue totalValue: Суммарное значение: #{totalValue}
AggregatedValue v: Суммарное значение #{v}
CumulativeWeightNotNormal: Совокупный вес не находится в диапазоне 0-1
WeightNotNormal: Вес не нормализован в диапазоне 0-1
Toggle: Переключать
ExpertAssessment: Оценка эксперта
CalculationAnalysis: Анализ расчета
ShowTop: Показать первые
Top: Первые
FirstN n: Первые #{show n}
ShowFirstN n: Показать первые #{show n}
ShowFirst: Показать первые
Sections: Разделы
Photo: Фото
EnterNewValue: Введите новое значение
NewValue: Новое значение
Age: Возраст
Attributes: Атрибуты
Birthday: День рождения
Tag: Ярлык
Tags: Ярлыки
Label: Ярлык
Labels: Ярлыки
RemoveSubdivision: Удалить подразделение
AddSubdivision: Добавить подразделение
Division: Подразделение
Divisions: Подразделения
NumberOfCandidates: Количество кандидатов
EnterNewName: Введите новое имя
Category: Категория
CreateCategory: Добавить категорию
Categories: Категории
InQuotes x: «#{x}»
EditSkills: Редактировать навыки
NSkills: Кол. навыков
NumberOfSkills: Количество навыков
Breadcrumbs: Хлебные крошки
Undefined: Не определено
Details: Подробности
NotFound: Не найдено
Overview: Обзор
SeeLink: См.
CreatePosition: Создать должность
EditPosition: Редактировать должность
Actions: Действия
Back: Вернуться
Candidate: Кандидат
SelectApplicants: Выберите соискателей
SelectPosition: Выберите должность
SelectAPosition: Выберите должность
InvalidArguments: Недопустимые аргументы
NumberSign: №
Position: Должность
DayEnd: Дата окончания
DayStart: Дата начала
Id: Идентификатор
Weight: Вес
SelectFromList: Выбрать из списка
Select: Выбрать
Close: Закрыть
Patronymic: Отчество
Surname: Фамилия
Name: Имя
FullName: ФИО
Applicants: Соискатели
Applicant: Соискатель
NoDataFound: Данные не найдены
RowsPerPage: Строк на странице
Last: Последняя
Next: Следующая
Previous: Предыдущая
First: Первая
PaginationLabel s e n: Запись #{show s} - #{show e} из #{show n}
Pagination: Пагинация
Clear: Очистить
InvalidFormData: Неверные данные формы
ReallyRemove: Вы действительно хотите удалить эту запись?
ReallyDelete: Вы действительно хотите удалить эту запись?
PleaseConfirm: Пожалуйста подтвердите
Remove: Удалить
Delete: Удалить
Edit: Редактировать
InputForm: Форма ввода
NewSkill: Новый навык
Description: Описание
Denom: Наименование
Code: Код
Cancel: Отмена
Save: Сохранить
Add: Добавить
Search: Поиск
Skill: Навык
Skills: Навыки
Positions: Должности
Candidates: Кандидаты
Profile: Профиль
Exit: Выход
HomePage: Домашняя страница
Home: Главная
ToggleNavigation: Переключить навигацию
AppName: Кандидат
MetaKeywords: Ранжирование, Навыки, Агрегация, Иерархический
MetaDescription: Метод объединения (агрегации) иерархических ранжирований, Подбор кандидатов на основе иерархии атрибутов

Doc1: Ранжирование кандидатов
Doc11: Это приложение предоставляет простой метод объединения (агрегации) иерархических ранжирований
Doc111: Приложение помогает принимать решения о подборе кандидатов на основе иерархии атрибутов, навыков и их веса
Doc12: Навыки, необходимые для должности, должны быть определены в словаре
Doc13: Должности и требуемые для них навыки определены в разделе
Doc14: Соискатели и их навыки добавляются в раздел
Doc15: Для каждой должности рассчитывается рейтинг кандидатов и результат доступен по ссылке «Кандидат»
Doc16: Также в разделе «Кандидаты» предоставлено больше возможностей для расчета рейтинга кандидатов
Doc18: Навык идентифицируется коротким кодом. У него есть имя и описание. Навык может быть атрибутом должности и/или соискателя.
Doc19: Должность определяется кодом. Ему присваивается имя, дата начала, дата окончания и, возможно, подразделение. Кроме того, Должность имеет отношение «многие ко многим» с Навыками. Каждой связи «Должность — Навык» присваивается вес Навыка или группы. Навыки могут быть сгруппированы. И группы могут быть дополнительно сгруппированы в иерархию.
Doc20: Соискатель — это сущность, чьи Навыки будут сопоставлены с Навыками, необходимыми для Должности.
Doc21: Кандидат — это Соискатель, чьи Навыки были сопоставлены с Навыками конкретной Должности, и для которого рассчитывается совокупный Вес (рейтинг), чтобы отличить его от других Соискателей на ту же Должность.