
static-dir:     "_env:YESOD_STATIC_DIR:static"
host:           "_env:YESOD_HOST:*4"
port:           "_env:YESOD_PORT:3000"

ip-from-header: "_env:YESOD_IP_FROM_HEADER:false"

database:
  database: "_env:YESOD_SQLITE_DATABASE:':memory:'"
  poolsize: "_env:YESOD_SQLITE_POOLSIZE:1"

copyright: Sergiu Starciuc
